livre_index:
    path:     /
    defaults: { _controller: "AdminBackBundle:Livre:index" }
    methods:  GET

livre_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBackBundle:Livre:show" }
    methods:  GET

livre_new:
    path:     /new
    defaults: { _controller: "AdminBackBundle:Livre:new" }
    methods:  [GET, POST]

livre_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBackBundle:Livre:edit" }
    methods:  [GET, POST]

livre_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBackBundle:Livre:delete" }
    methods:  DELETE
